<?php

namespace AppBundle\Repository;

/**
 * CertificateCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificateCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
