<?php

namespace AppBundle\Repository;

/**
 * CourseModuleAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseModuleAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
