<?php

namespace AppBundle\Repository;

/**
 * CourseModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
