<?php

namespace AppBundle\Repository;

/**
 * CourseModuleQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseModuleQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
