<?php

namespace AppBundle\Repository;

/**
 * EventItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventItemRepository extends \Doctrine\ORM\EntityRepository
{
}
