<?php

namespace AppBundle\Repository;

/**
 * EventRegisterLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRegisterLogRepository extends \Doctrine\ORM\EntityRepository
{
}
