<?php

namespace AppBundle\Repository;

/**
 * GaleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleryRepository extends \Doctrine\ORM\EntityRepository
{
}
