<?php

namespace AppBundle\Repository;

/**
 * InterviewChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterviewChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
