<?php

namespace AppBundle\Repository;

/**
 * InterviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterviewRepository extends \Doctrine\ORM\EntityRepository
{
}
