<?php

namespace AppBundle\Repository;

/**
 * OrganizaationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizaationRepository extends \Doctrine\ORM\EntityRepository
{
}
