<?php

namespace AppBundle\Repository;

/**
 * PrezidiumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrezidiumRepository extends \Doctrine\ORM\EntityRepository
{
}
