<?php

namespace AppBundle\Repository;

/**
 * RecordBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordBookRepository extends \Doctrine\ORM\EntityRepository
{
}
