<?php

namespace AppBundle\Repository;

/**
 * RecomendationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommendationRepository extends \Doctrine\ORM\EntityRepository
{
}
