<?php

namespace AppBundle\Repository;

/**
 * SlidebarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlidebarRepository extends \Doctrine\ORM\EntityRepository
{
}
