<?php

namespace AppBundle\Repository;

/**
 * SpecialtyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialtyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {

        $orderBy['sort'] = 'ASC';
        return parent::findBy($criteria, $orderBy, $limit, $offset); // TODO: Change the autogenerated stub
    }

    public function findAll()
    {
        $orderBy['sort'] = 'ASC';
        return parent::findBy([], $orderBy);
    }
}
