<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function statsByCity(){
        $qb = $this->createQueryBuilder('u');
        $qb->select('c.title title, COUNT(u.id) cc');
        $qb->leftJoin('u.city', 'c')
            ->andWhere("s.enabled = 1")
            ->orderBy('count', 'DESC');
        $result = $qb->getQuery()->getResult();

        return $result;
    }

    public function statsBySpecialty(){
        $qb = $this->createQueryBuilder('u');
        $qb->select('c.title title, COUNT(u.id) cc');
        $qb->leftJoin('u.specialty', 'c')
            ->andWhere("s.enabled = 1")
            ->orderBy('count', 'DESC');
        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
